# Data Splitting

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

df = pd.read_csv("D:\Documents\Projects\Machine Learning\Datathon\LAPTOP MODEL\DATASETFINAL.csv")

df.head()

<>:6: SyntaxWarning: invalid escape sequence '\D'
<>:6: SyntaxWarning: invalid escape sequence '\D'
C:\Users\nadhi\AppData\Local\Temp\ipykernel_4904\3407294896.py:6: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv("D:\Documents\Projects\Machine Learning\Datathon\LAPTOP MODEL\DATASETFINAL.csv")


no   Brand   CPU  GPU RAM Type  RAM Size  Storage Screen Type  \
0   1    ACER  8531  NaN     DDR5         8      512         IPS   
1   2    ASUS  8657  NaN     DDR5        16      256         IPS   
2   3      HP  8657  NaN     DDR4        16      512         IPS   
3   4  LENOVO  8657  NaN     DDR5         8      256         IPS   
4   5    ACER  5491  NaN     DDR4         8      512         IPS   

   Refresh Rate  Uniqueness  Upgradeable    price  points        worth  
0            60           0            1  5054831    9990  well-priced  
1            60           0            1  5099000   10013  well-priced  
2            60           0            1  5139000    9673  well-priced  
3            60           0            0  5199000    7589  well-priced  
4            60           0            1  5229000    7268  well-priced

In [3]:
X = pd.get_dummies(df.drop(["points", "worth"], axis=1))
y = df["worth"]

X = X.fillna(0)



In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection

In [5]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

model = make_pipeline(StandardScaler(),GradientBoostingClassifier())

model.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gradientboostingclassifier', GradientBoostingClassifier())])

In [6]:
y_pred = model.predict(X_test)



# Validation Score

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

cm = confusion_matrix(y_test, y_pred)
sc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"F1: {f1}")
print(f"SC: {sc} \n" )

print(cm)

F1: 0.8956066697821474
SC: 0.8982300884955752 

[[  0   0   0   0   0]
 [  0   2   0   0   2]
 [  0   0 174   4   0]
 [  0   0   5  14   2]
 [  1   0   5   4  13]]


# Real Test 


In [8]:
#import pickle

#with open ('SGDRegression.pkl', 'wb') as files:
    #pickle.dump(model,files)